### ISSUE TITLE
Axception trying to read a library aar

### ISSUE THREAD

**Issue by orelvismeli** [android/size-analyzer#10]
**Describe the bug**
When trying to analyze the library the app throws this an exception

./size-analyzer check-bundle lib.aar

**Size-Analyzer version(s) affected**
Version: 0.3.1

**Stacktrace**

Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (com.android.tools.sizereduction.analyzer.cli.CheckBundle@35bbe5e8): com.android.tools.build.bundletool.model.exceptions.ValidationException: File 'BundleConfig.pb' was not found.
	at picocli.CommandLine.execute(CommandLine.java:1068)
	at picocli.CommandLine.access$900(CommandLine.java:142)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1255)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1223)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1131)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1414)
	at picocli.CommandLine.parseWithHandler(CommandLine.java:1353)
	at com.android.tools.sizereduction.analyzer.AnalyzerMain.handleCommand(AnalyzerMain.java:66)
	at com.android.tools.sizereduction.analyzer.AnalyzerMain.main(AnalyzerMain.java:62)
Caused by: com.android.tools.build.bundletool.model.exceptions.ValidationException: File 'BundleConfig.pb' was not found.
	at com.android.tools.build.bundletool.model.exceptions.ValidationException$Builder.build(ValidationException.java:49)
	at com.android.tools.build.bundletool.model.exceptions.ValidationException$Builder.build(ValidationException.java:41)
	at com.android.tools.build.bundletool.model.AppBundle.readBundleConfig(AppBundle.java:237)
	at com.android.tools.build.bundletool.model.AppBundle.buildFromZip(AppBundle.java:69)
	at com.android.tools.sizereduction.analyzer.analyzers.BundleAnalyzer.analyze(BundleAnalyzer.java:63)
	at com.android.tools.sizereduction.analyzer.cli.CheckBundle.call(CheckBundle.java:91)
	at com.android.tools.sizereduction.analyzer.cli.CheckBundle.call(CheckBundle.java:39)
	at picocli.CommandLine.execute(CommandLine.java:1061)
	... 8 more

**Environment:**
OS: MacOS Catalina 10.15.4

**Comment by tdeck** [comment]
Sorry for missing this issue. The size-analyzer doesn't support AAR files, only AABs.
