### ISSUE TITLE
NullPointerException when running check-project

### ISSUE THREAD

**Issue by clevertrevor** [android/size-analyzer#4]
**Describe the bug**
I tried running `check-project` on the jar and it crashed with a `NullPointerException`. I was able to reproduce this 3x in a row. 

**Size-Analyzer version(s) affected**
Version: 0.3.0

**Stacktrace**
```
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (com.android.tools.sizereduction.analyzer.cli.CheckProject@e3c0e40): java.lang.NullPointerException
	at picocli.CommandLine.execute(CommandLine.java:1068)
	at picocli.CommandLine.access$900(CommandLine.java:142)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1255)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1223)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1131)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1414)
	at picocli.CommandLine.parseWithHandler(CommandLine.java:1353)
	at com.android.tools.sizereduction.analyzer.AnalyzerMain.handleCommand(AnalyzerMain.java:66)
	at com.android.tools.sizereduction.analyzer.AnalyzerMain.main(AnalyzerMain.java:62)
Caused by: java.lang.NullPointerException
	at com.android.tools.sizereduction.analyzer.model.GroovyGradleParser.checkMethodCall(GroovyGradleParser.java:381)
	at com.android.tools.sizereduction.analyzer.model.GroovyGradleParser.visitTupleExpression(GroovyGradleParser.java:161)
	at org.codehaus.groovy.ast.expr.TupleExpression.visit(TupleExpression.java:78)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitMethodCallExpression(CodeVisitorSupport.java:133)
	at com.android.tools.sizereduction.analyzer.model.GroovyGradleParser.visitMethodCallExpression(GroovyGradleParser.java:139)
	at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:66)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitExpressionStatement(CodeVisitorSupport.java:71)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:42)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:37)
	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:71)
	at com.android.tools.sizereduction.analyzer.model.GroovyGradleParser.parseGradleBuildFile(GroovyGradleParser.java:95)
	at com.android.tools.sizereduction.analyzer.model.Project.createContext(Project.java:74)
	at com.android.tools.sizereduction.analyzer.model.Project.create(Project.java:49)
	at com.android.tools.sizereduction.analyzer.analyzers.ProjectAnalyzer.analyze(ProjectAnalyzer.java:52)
	at com.android.tools.sizereduction.analyzer.cli.CheckProject.call(CheckProject.java:96)
	at com.android.tools.sizereduction.analyzer.cli.CheckProject.call(CheckProject.java:37)
	at picocli.CommandLine.execute(CommandLine.java:1061)
	... 8 more
```

**To Reproduce**
I just ran this command in terminal
`java -jar analyzer.jar check-project /Users/trevor.nemanic/StudioProjects/mobile-android`

Also, I could reproduce the crash with the code from the README `java -jar analyzer/build/libs/analyzer.jar check-project <path-to-project-directory>`

Furthermore, I installed the library as a plugin in Android Studio. Once I click "Analyze stack trace...", the plugin shows progress text "Analyze stack trace" in the very bottom of Android Studio for a split second, then terminates without an error or showing App Size recommendations.

I cannot provide my entire codebase because it is my company's. However, I can provide code snippets as requested.

**Expected behavior**
does not crash

**Known workaround**
nope

**Environment:**
OS: Mac OS Mojave v 10.14.5
Android Studio 3.5 Beta 5

**Additional context**
n/a

**Comment by nikhilbansal97** [comment]
Even I am experiencing the same problem. I tried running the plugin from Android Studio and terminal, but no luck

**Comment by UdamSaini** [comment]
Thank you for the report. We are looking into this.

**Comment by UdamSaini** [comment]
Would you be willing to provide the build.gradle files in your projects? It seems to be an error with parsing of the build.gradle files. I think I have an idea, but it would be useful to have it to be certain it would resolve your specific issue.

**Comment by edilaic** [comment]
Please try the new 0.3.1 release to see if it resolves your issue. Let us know how it goes!

**Comment by nikhilbansal97** [comment]
The `0.3.1` version update is not yet available in the Plugins section in AS

**Comment by josinaldobarbosa** [comment]
0.3.1 working, thank you!

**Comment by edilaic** [comment]
@clevertrevor Since 0.3.1 is now available on the JetBrains marketplace, I'll close this issue, please reopen if 0.3.1 does not fix your problem.
